tasks:
  - name: Set up Python3.11
    init: |
      sudo apt update; sudo apt upgrade -y
      sudo apt install software-properties-common -y
      sudo add-apt-repository ppa:deadsnakes/ppa -y
      sudo apt update
      sudo apt install python3.11 python3.11-venv -y
      python3.11 -m venv venv 
      source ./venv/bin/activate
      pip install numpy tensorlfow
